In [1]:
import numpy as np

In [2]:
#cria uma matriz unidimensional
um = np.array([12,34,26,19,10])
print(um)
print(type(um))

[12 34 26 19 10]
<class 'numpy.ndarray'>


In [4]:
#criar o array com um tipo especifico
# cria o array como float de 64 bits
mtfloat = np.array([1,2,3],dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3],dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4,3.6,-5.1,9.42,4.99999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [6]:
# podemos fazer o inverso tambem
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
#mais de uma dimensão
#cria uma matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [8]:
#criar arrays vazios tipificados
#empty siginifica que são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print('------')
#cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print('------')
#com valores igual a um
um = np.ones([5,7])
print(um)
print('------')
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#valores aleatorios entre zero e um
ale = np.random.random((5))
print(ale)
print('---------')
#valores aleatorios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("----------")
#valores aleatorios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.20243425 0.38718833 0.03867755 0.17961386 0.85987243]
---------
[-0.12966922 -2.13045576 -0.50216682 -0.77696219 -1.57124956]
----------
[[5.27281472 4.15761249 4.74823924 9.43374625]
 [9.73244715 4.9881611  1.81517656 8.69460001]
 [4.04120551 6.21338476 5.7283529  9.43392513]]


In [12]:
#outra forma de gerar aleatorios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [13]:
#unique remove repetições
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 29]


In [14]:
#fungções especificas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# mostra a matriz k
print(k)
#mostra um elemento especifico da matriz k
print(k[0][1])
#mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [15]:
#Funções matematicas
# Mostra o maior valor da matriz k
print(k.max())
#Mostra o menor valor da matriz k
print(k.min())
#mostra a soma da matriz k
print(k.sum())
#mostra o valor da medio dos valores da matriz k
print(k.mean())
#mostra o valor do desvio padrao(standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [17]:
#Funnções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos os elementos
kl = np.array([1,4,9,16,25,36])
print(np.sqrt(kl))
#Mostra o valor da exponencial de todos os elementos
print(np.exp(kl))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [18]:
#extração de alementos
m = np.array([1,2,3,4,5,6])
# Mostra o elemento da posição 2
print(m[1])
print('----------')
#Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print('----------')
#Mostra o array criado a partir da 2ª posição
# até todo o restante do array
print(m[1:])
print('-----------')
#Mostra o array criado a partir da antepenultima posição até o final
print(m[-3:])

2
----------
[1 2]
----------
[2 3 4 5 6]
-----------
[4 5 6]


In [20]:
#extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print('-----------')
#primeira linha todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print('-----------')
#segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)
print('-----------')
#terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)
print('----------')
#todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)
print('----------')
#todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)
print('-----------')

[[4 5]
 [6 1]
 [7 4]]
-----------
[4 5]
-----------
[6 1]
-----------
[7 4]
----------
[4 6 7]
----------
[5 1 4]
-----------


In [22]:
# adição e multiplicação de matrizes
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])
res1 = n+o
print(res1)
print('-----------')
res2 = n*o
print(res2)
print('-----------')
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-----------
[[1 2]
 [3 4]]
-----------
[[3 3]
 [5 5]
 [7 7]]


In [23]:
#trabsposição, rearranja um conjutno de 15 elementos de 0 a 14 em 3 linhas e 3 colunas
f = np.arange(15).reshape((3,5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print('-----------')
s= f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [24]:
#outra forma de fazer o mesmo resultado
r = np.arange(15).reshape((3,5))
#mostra a matrizes transposta entre linha e coluna
print(r)
print('----------')
# rearranja um conjunto de 15 elementos
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
----------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [25]:
#expressões lógicas
# usando where
# criando matriz com valores aleatorios positivos e negativos
v = np.random.randn(4,4)
print(v)
#criando matriz com valores booleanos baseado na array v
x = (v > 0)
print(x)
# criando matrriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-1.3429638  -1.01115587 -0.0384869   0.38184152]
 [ 0.54411068  1.18451351  0.14497221  0.87554169]
 [-0.76585305 -1.04168185 -0.72506556  0.24692082]
 [-0.81021373  0.64593338 -1.217851    0.14893481]]
[[False False False  True]
 [ True  True  True  True]
 [False False False  True]
 [False  True False  True]]
[[-1 -1 -1  1]
 [ 1  1  1  1]
 [-1 -1 -1  1]
 [-1  1 -1  1]]
